[[entries]]
title = "A Guide for an HP Warrior!"
date = 2006-05-07
media = ["text", "images"]
subjects = ["guide", "HP warrior", "pre-BB", "GMS"]
domain = "sleepywood.net"
url_archived = "https://web.archive.org/web/20120614133139/http://sleepywood.net/forum/showthread.php?t=891610"

[[entries]]
title = "LUK Warrior"
date = 2007-02-06
media = ["text"]
subjects = ["LUK warrior", "pre-BB", "GMS"]
domain = "hidden-street.net"
url = "https://www.hidden-street.net/forum/threads/13250-LUK-Warrior"
url_archived = "https://web.archive.org/web/20210103200552/https://www.hidden-street.net/forum/threads/13250-LUK-Warrior"

[[entries]]
title = "STR Mage v3"
date = 2007-03-04
media = ["text", "images"]
subjects = ["guide", "gish", "STR mage", "fire/poison", "pre-BB", "GMS"]
domain = "hidden-street.net"
url = "https://www.hidden-street.net/forum/threads/14161-STR-Mage-v3"
url_archived = "https://web.archive.org/web/20201228092416/https://www.hidden-street.net/forum/threads/14161-STR-Mage-v3"

[[entries]]
title = "Woodsmen"
date = 2007-08-12
media = ["text"]
subjects = ["woodsman", "pre-BB", "GMS"]
domain = "hidden-street.net"
url = "https://www.hidden-street.net/forum/threads/21249-Woodsmen"
url_archived = "https://web.archive.org/web/20210103211159/https://www.hidden-street.net/forum/threads/21249-Woodsmen"

[[entries]]
title = "Brandini's Islander Guide"
date = 2007-11-05
media = ["text"]
subjects = ["guide", "islander", "magelander", "pre-BB", "GMS"]
domain = "mapletip.com"
url = "https://forums.mapletip.com/index.php?/topic/111589-brandinis-islander-guide/"
url_archived = "https://web.archive.org/web/20180124095048/https://forums.mapletip.com/index.php?/topic/111589-brandinis-islander-guide/"

[[entries]]
title = "War mage (STR Mage) Guide"
date = 2007-12-05
media = ["text"]
subjects = ["guide", "STR mage", "cleric", "pre-BB", "GMS"]
domain = "mapletip.com"
url = "https://forums.mapletip.com/index.php?/topic/113500-war-mage-str-mage-guide/"
url_archived = "https://web.archive.org/web/20140708111804/https://forums.mapletip.com/index.php?/topic/113500-war-mage-str-mage-guide/"

[[entries]]
title = "3 STR Mages + 1 Beginner / 1 Warrior = KPQ Ownage"
date = 2008-01-19
media = ["video", "audio"]
subjects = ["STR mage", "permabeginner", "PQ", "pre-BB", "GMS"]
domain = "youtube.com"
url = "https://www.youtube.com/watch?v=j1RRtSa_C9Q"

[[entries]]
title = "Top Beginner Archive"
date = 2008-01-30
media = ["text"]
subjects = ["camper", "islander", "permabeginner", "rankings", "pre-BB", "GMS"]
domain = "tapatalk.com"
url = "https://www.tapatalk.com/groups/permbeginners/top-beginner-archive-t2.html"
url_archived = "https://web.archive.org/web/20210513110934/https://www.tapatalk.com/groups/permbeginners/top-beginner-archive-t2.html"

[[entries]]
title = "A Tribute to Strength Mages (HematicBlade's Story)"
date = 2008-06-20
media = ["video", "audio"]
subjects = ["STR mage", "pre-BB", "GMS"]
domain = "youtube.com"
url = "https://www.youtube.com/watch?v=ciQHAq2ckDo"

[[entries]]
title = "The Complete HP Warrior guide from Levels 1-30"
date = 2008-06-27
media = ["text"]
subjects = ["guide", "HP warrior", "pre-BB", "GMS"]
domain = "mapletip.com"
url = "https://forums.mapletip.com/index.php?/topic/124215-the-complete-hp-warrior-guide-from-levels-1-30/"
url_archived = "https://web.archive.org/web/20140708143118/https://forums.mapletip.com/index.php?/topic/124215-the-complete-hp-warrior-guide-from-levels-1-30/"

[[entries]]
title = "Sean's Guide to a Perfect STR Mage"
date = 2008-11-18
media = ["text"]
subjects = ["guide", "STR mage", "cleric", "pre-BB", "GMS"]
domain = "hidden-street.net"
url = "https://www.hidden-street.net/forum/threads/34198-Sean-s-Guide-to-a-Perfect-STR-Mage"
url_archived = "https://web.archive.org/web/20200529171616/https://www.hidden-street.net/forum/threads/34198-Sean-s-Guide-to-a-Perfect-STR-Mage"

[[entries]]
title = "MapleStory Guide for Beginner Permanent Part One"
date = 2008-12-08
media = ["text"]
subjects = ["guide", "permabeginner", "pre-BB", "GMS"]
domain = "centerblog.net"
url = "http://pwpw.centerblog.net/6558496-MapleStory-Guide-for-Beginner-Permanent-Part-One"
url_archived = "https://web.archive.org/web/20170102145913/http://pwpw.centerblog.net/6558496-MapleStory-Guide-for-Beginner-Permanent-Part-One"

[[entries]]
title = "Permanent Beginner Guide"
date = 2009-09-19
media = ["text"]
subjects = ["guide", "permabeginner", "islander", "camper", "pre-BB", "GMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20110906023805/http://www.basilmarket.com/MapleStory-Guide-Permanent-Beginner-201.html"

[[entries]]
title = "Readers' Extraordinary Permanent Beginner Guide"
date = 2009-11-25
media = ["text"]
subjects = ["guide", "permabeginner", "islander", "camper", "pre-BB", "GMS"]
domain = "mapletip.com"
url = "https://forums.mapletip.com/index.php?/topic/139169-readers-extraordinary-permanent-beginner-guide/"
url_archived = "https://web.archive.org/web/20200806122805/https://forums.mapletip.com/index.php?/topic/139169-readers-extraordinary-permanent-beginner-guide/"

[[entries]]
title = "So are there any Dagger Warriors at all?"
date = 2009-12-05
media = ["text"]
subjects = ["dagger warrior", "STR mage", "pre-BB", "GMS"]
domain = "gamespot.com"
url = "https://gamefaqs.gamespot.com/boards/924697-maplestory/52541643"
url_archived = "https://web.archive.org/web/20210103201515/https://gamefaqs.gamespot.com/boards/924697-maplestory/52541643"

[[entries]]
title = "Guide to Perma Beginners"
date = 2009-12-28
media = ["text"]
subjects = [
    "guide",
    "permabeginner",
    "islander",
    "woodsman",
    "bow-whacker",
    "brigand",
    "STR mage",
    "pre-BB",
    "GMS",
]
domain = "blogspot.com"
url = "https://maplestorymesos2009.blogspot.com/2009/12/guide-to-perma-beginners.html"
url_archived = "https://web.archive.org/web/20210103204521/https://maplestorymesos2009.blogspot.com/2009/12/guide-to-perma-beginners.html"

[[entries]]
title = "General List of Experimental Classes"
date = 2010-01-13
media = ["text"]
subjects = ["general", "post-BB", "pre-BB", "GMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20200217044826/http://www.basilmarket.com/Other-General-List-of-Experimental-Classes-Wiki-2993"

[[entries]]
title = "Complete Islander Guide"
date = 2010-03-20
media = ["text"]
subjects = ["guide", "islander", "pre-BB", "GMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20190822160827/https://www.basilmarket.com/Complete-Islander-Guide-Thread-bqpNW-1"

[[entries]]
title = "Table - MapleStory Europe's Number 1 Islander"
date = 2010-04-22
media = ["video", "audio"]
subjects = ["islander", "pre-BB", "EMS"]
domain = "youtube.com"
url = "https://www.youtube.com/playlist?list=PL1F64856377524CD8"

[[entries]]
title = "Comprehensive Guide to Jobless Characters Part 2"
date = 2010-05-13
media = ["text"]
subjects = ["permabeginner", "guide", "pre-BB", "GMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20100516173343/http://www.basilmarket.com/forum/1508788/0/Comprehensive_Guide_to_Jobless_Characters_Part_2.html"

[[entries]]
title = "Beginner Damage Ranges"
date = 2010-06-02
media = ["text"]
subjects = ["permabeginner", "islander", "pre-BB", "GMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20110727034426/http://www.basilmarket.com/MapleStory-Guide-Beginner-Damage-Ranges-287.html"

[[entries]]
title = "DuFyy's Beginner Guide"
date = 2010-06-20
media = ["text"]
subjects = ["guide", "permabeginner", "islander", "camper", "pre-BB", "GMS"]
domain = "mapleanime.com"
url = "https://www.mapleanime.com/forum/viewtopic.php?t=6216"
url_archived = "https://web.archive.org/web/20201228114125/https://www.mapleanime.com/forum/viewtopic.php?t=6216"

[[entries]]
title = "Okay, could someone tell me where a brigand should grind?"
date = 2010-11-23
media = ["text"]
subjects = ["brigand", "pre-BB", "GMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20200221183446/https://www.basilmarket.com/Okay-could-someone-tell-me-where-a-brigand-should-grind-Thread-bwkbz-1"

[[entries]]
title = "MapleStory GMS - HP Warrior tanks 50k damage"
date = 2011-06-10
media = ["video", "audio"]
subjects = ["HP warrior", "post-BB", "GMS"]
domain = "youtube.com"
url = "https://www.youtube.com/watch?v=xjEutlW_5Nc"

[[entries]]
title = "Perma Beginner"
date = 2011-10-27
media = ["text"]
subjects = ["permabeginner", "post-BB", "TMS", "GMS"]
domain = "maplewiki.net"
url_archived = "https://web.archive.org/web/20120418093340/https://maplewiki.net/index.php?title=Perma_Beginner"

[[entries]]
title = "Islander"
date = 2011-11-27
media = ["text"]
subjects = ["islander", "camper", "post-BB", "pre-BB", "GMS"]
domain = "maplewiki.net"
url_archived = "https://web.archive.org/web/20120418085300/https://maplewiki.net/index.php?title=Islander"

[[entries]]
title = "How Many Odd Jobs Do You Have?"
date = 2012-04-01
media = ["text"]
subjects = ["general", "post-BB", "GMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20200216222634/https://www.basilmarket.com/How-Many-Odd-Jobs-Do-You-Have-Thread-b1v6E-1"

[[entries]]
title = "Str Mage Guide"
date = 2012-06-12
media = ["text"]
subjects = ["guide", "STR Mage", "post-BB", "GMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20200216182956/https://www.basilmarket.com/Str-Mage-Guide-Thread-b1DGx-1"

[[entries]]
title = "Str Mages?"
date = 2012-11-16
media = ["text"]
subjects = ["general", "STR mage", "post-BB", "GMS"]
domain = "reddit.com"
url = "https://old.reddit.com/r/Maplestory/comments/13bn69/str_mages/"
url_archived = "https://web.archive.org/web/20201228101000/https://old.reddit.com/r/Maplestory/comments/13bn69/str_mages/"

[[entries]]
title = "Warrior: Builds: Alternative builds"
date = 2013-04-03
media = ["text"]
subjects = ["HP warrior", "dagger warrior", "post-BB", "GMS"]
domain = "strategywiki.org"
url = "https://strategywiki.org/wiki/MapleStory/Warrior/Builds#Alternative_builds"
url_archived = "https://web.archive.org/web/20170719140309/https://strategywiki.org/wiki/MapleStory/Warrior/Builds#Alternative_builds"

[[entries]]
title = "[In-Depth] Shadower Guide"
date = 2014-05-05
media = ["text"]
subjects = ["blood bandit", "pre-BB", "MapleRoyals"]
domain = "mapleroyals.com"
url = "https://mapleroyals.com/forum/threads/in-depth-shadower-guide.8122/"
url_archived = "https://web.archive.org/web/20160716031114/http://mapleroyals.com:80/forum/threads/in-depth-shadower-guide.8122/"

[[entries]]
title = "Islander Community Rankings / Guides"
date = 2014-12-08
media = ["text", "images"]
subjects = [
    "islander",
    "magelander",
    "camper",
    "guide",
    "rankings",
    "pre-BB",
    "MapleRoyals",
]
domain = "mapleroyals.com"
url = "https://mapleroyals.com/forum/threads/islander-community-rankings-guides.17081/"
url_archived = "https://web.archive.org/web/20201230115238/https://mapleroyals.com/forum/threads/islander-community-rankings-guides.17081/"

[[entries]]
title = "2015: General Odd-Job Discussion"
date = 2015-05-18
media = ["text"]
subjects = ["general", "post-BB", "GMS"]
domain = "reddit.com"
url = "https://old.reddit.com/r/Maplestory/comments/36cdae/2015_general_oddjob_discussion/"
url_archived = "https://web.archive.org/web/20201228085257/https://old.reddit.com/r/Maplestory/comments/36cdae/2015_general_oddjob_discussion/"

[[entries]]
title = "Alyssaur's Kind of Unnecessary Compilation of Unusual Builds"
date = 2015-07-17
media = ["text"]
subjects = ["general", "pre-BB", "MapleRoyals", "GMS"]
domain = "mapleroyals.com"
url = "https://mapleroyals.com/forum/threads/alyssaurs-kind-of-unnecessary-compilation-of-unusual-builds.32333/"
url_archived = "https://web.archive.org/web/20210101092152/https://mapleroyals.com/forum/threads/alyssaurs-kind-of-unnecessary-compilation-of-unusual-builds.32333/"

[[entries]]
title = "Islander Community Thread"
date = 2015-09-28
media = ["text"]
subjects = ["islander", "magelander", "guide", "pre-BB", "MapleLegends"]
domain = "maplelegends.com"
url = "https://forum.maplelegends.com/index.php?threads/islander-community-thread.5922/"
url_archived = "https://web.archive.org/web/20201230122138/https://forum.maplelegends.com/index.php?threads/islander-community-thread.5922/"

[[entries]]
title = "Does anyone remember Islander Beginners?"
date = 2015-12-24
media = ["text", "images"]
subjects = ["islander", "pre-BB", "post-BB", "GMS", "EMS"]
domain = "reddit.com"
url = "https://old.reddit.com/r/Maplestory/comments/3y4qvd/does_anyone_remember_islander_beginners/"
url_archived = "https://web.archive.org/web/20201230163024/https://old.reddit.com/r/Maplestory/comments/3y4qvd/does_anyone_remember_islander_beginners/"

[[entries]]
title = "Disoriented's Permanent Beginner Guide!"
date = 2016-06-03
media = ["text", "images"]
subjects = ["guide", "permabeginner", "pre-BB", "MapleRoyals"]
domain = "mapleroyals.com"
url = "https://mapleroyals.com/forum/threads/disorienteds-permanent-beginner-guide.67505/"
url_archived = "https://web.archive.org/web/20210101091315/https://mapleroyals.com/forum/threads/disorienteds-permanent-beginner-guide.67505/"

[[entries]]
title = "KMS STR Mage"
date = 2017-05-29
media = ["images", "text"]
subjects = ["STR mage", "fire/poison", "pre-BB", "KMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20180311145509/https://www.basilmarket.com/KMS-STR-Mage-Screen-bbZzO"

[[entries]]
title = "KMS permanent beginner ranker(2003-2005)"
date = 2017-05-29
media = ["images", "text"]
subjects = ["permabeginner", "pre-BB", "KMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20180320175401/http://www.basilmarket.com/KMS-permanent-beginner-ranker-2003-2005--Screen-bbZzP"

[[entries]]
title = "The pioneer of poison mist str mage(KMS)"
date = 2017-06-01
media = ["images", "text"]
subjects = ["STR mage", "fire/poison", "pre-BB", "KMS"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20170809123316/http://www.basilmarket.com/The-pioneer-of-poison-mist-str-mage-KMS--Screen-bbZzQ"

[[entries]]
title = "[KMS] 2017 Maplestory Camper - The last active Islander"
date = 2017-12-19
media = ["video", "audio"]
subjects = ["camper", "post-BB", "KMS"]
domain = "youtube.com"
url = "https://www.youtube.com/watch?v=s9SXRQGwvRA"

[[entries]]
title = "JoblessMS"
date = 2018-01-20
media = ["text", "images"]
subjects = ["general", "pre-BB", "JoblessMS"]
domain = "bladenode.com"
url_archived = "https://web.archive.org/web/20180120134715/http://server72.bladenode.com/?base=main"

[[entries]]
title = "Producer's Permanent Beginner Guide"
date = 2019-06-11
media = ["text"]
subjects = ["guide", "permabeginner", "post-BB", "GMS"]
domain = "dexless.com"
url = "https://dexless.com/guides/producers-permanent-beginner-guide.128/"
url_archived = "https://web.archive.org/web/20201230122744/https://dexless.com/guides/producers-permanent-beginner-guide.128/"

[[entries]]
title = "JoblessMS Rankings"
date = 2019-12-30
media = ["text", "images"]
subjects = ["rankings", "pre-BB", "JoblessMS"]
domain = "bladenode.com"
url = "http://server72.bladenode.com/?base=main&page=rankings"
url_archived = "https://web.archive.org/web/20191230014243/http://server72.bladenode.com/?base=main&page=rankings"

[[entries]]
title = "Found an old screenshot"
date = 2020-02-18
media = ["images"]
subjects = ["STR mage", "pre-BB", "GMS"]
domain = "reddit.com"
url = "https://old.reddit.com/r/Maplestory/comments/f5q2rx/found_an_old_screenshot/"
url_archived = "https://web.archive.org/web/20210103205959/https://old.reddit.com/r/Maplestory/comments/f5q2rx/found_an_old_screenshot/"

[[entries]]
title = "JoblessMS"
date = 2020-12-30
media = ["text", "images"]
subjects = ["general", "pre-BB", "JoblessMS"]
domain = "bladenode.com"
url = "http://server72.bladenode.com/?base=main"
url_archived = "https://web.archive.org/web/20201230194004/http://server72.bladenode.com/?base=main"

[[entries]]
title = "JoblessMS Guide"
date = 2021-01-01
media = ["images", "text"]
subjects = ["guide", "general", "pre-BB", "JoblessMS"]
domain = "bladenode.com"
url = "http://server72.bladenode.com/?base=main&page=guide"
url_archived = "https://web.archive.org/web/20210101095506/http://server72.bladenode.com/?base=main&page=guide"

[[entries]]
title = "The special beginners of Maplestory"
date = 2021-04-16
media = ["video", "audio"]
subjects = ["permabeginner", "post-BB", "GMS"]
domain = "youtube.com"
url = "https://www.youtube.com/watch?v=d4O5jouqay4"
