[[entries]]
title = "A Guide for an HP Warrior!"
date = 2006-05-07
media = ["text", "images"]
subjects = ["guide", "HP warrior", "pre-BB"]
domain = "sleepywood.net"
url_archived = "https://web.archive.org/web/20120614133139/http://sleepywood.net/forum/showthread.php?t=891610"

[[entries]]
title = "STR Mage v3"
date = 2007-03-04
media = ["text", "images"]
subjects = ["guide", "gish", "STR mage", "fire/poison", "pre-BB"]
domain = "hidden-street.net"
url = "https://www.hidden-street.net/forum/threads/14161-STR-Mage-v3"
url_archived = "https://web.archive.org/web/20201228092416/https://www.hidden-street.net/forum/threads/14161-STR-Mage-v3"

[[entries]]
title = "War mage (STR Mage) Guide"
date = 2007-12-05
media = ["text"]
subjects = ["guide", "STR mage", "cleric", "pre-BB"]
domain = "mapletip.com"
url = "https://forums.mapletip.com/index.php?/topic/113500-war-mage-str-mage-guide/"
url_archived = "https://web.archive.org/web/20140708111804/https://forums.mapletip.com/index.php?/topic/113500-war-mage-str-mage-guide/"

[[entries]]
title = "3 STR Mages + 1 Beginner / 1 Warrior = KPQ Ownage"
date = 2008-01-19
media = ["video", "audio"]
subjects = ["STR mage", "permabeginner", "PQ", "pre-BB"]
domain = "youtube.com"
url = "https://www.youtube.com/watch?v=j1RRtSa_C9Q"

[[entries]]
title = "A Tribute to Strength Mages (HematicBlade's Story)"
date = 2008-06-20
media = ["video", "audio"]
subjects = ["STR mage", "pre-BB"]
domain = "youtube.com"
url = "https://www.youtube.com/watch?v=ciQHAq2ckDo"

[[entries]]
title = "The Complete HP Warrior guide from Levels 1-30"
date = 2008-06-27
media = ["text"]
subjects = ["guide", "HP warrior", "pre-BB"]
domain = "mapletip.com"
url = "https://forums.mapletip.com/index.php?/topic/124215-the-complete-hp-warrior-guide-from-levels-1-30/"
url_archived = "https://web.archive.org/web/20140708143118/https://forums.mapletip.com/index.php?/topic/124215-the-complete-hp-warrior-guide-from-levels-1-30/"

[[entries]]
title = "Readers' Extraordinary Permanent Beginner Guide"
date = 2009-11-25
media = ["text"]
subjects = ["guide", "permabeginner", "islander", "camper", "pre-BB"]
domain = ["mapletip.com"]
url = "https://forums.mapletip.com/index.php?/topic/139169-readers-extraordinary-permanent-beginner-guide/"
url_archived = "https://web.archive.org/web/20200806122805/https://forums.mapletip.com/index.php?/topic/139169-readers-extraordinary-permanent-beginner-guide/"

[[entries]]
title = "DuFyy's Beginner Guide"
date = 2010-06-20
media = ["text"]
subjects = ["guide", "permabeginner", "islander", "camper", "pre-BB"]
domain = "mapleanime.com"
url = "https://www.mapleanime.com/forum/viewtopic.php?t=6216"
url_archived = "https://web.archive.org/web/20201228114125/https://www.mapleanime.com/forum/viewtopic.php?t=6216"

[[entries]]
title = "MapleStory GMS - HP Warrior tanks 50k damage"
date = 2011-06-10
media = ["video", "audio"]
subjects = ["HP warrior", "post-BB"]
domain = "youtube.com"
url = "https://www.youtube.com/watch?v=xjEutlW_5Nc"

[[entries]]
title = "Islander"
date = 2011-11-27
media = ["text"]
subjects = ["islander", "camper", "post-BB", "pre-BB"]
domain = "maplewiki.net"
url = "https://web.archive.org/web/20120418085300/https://maplewiki.net/index.php?title=Islander"

[[entries]]
title = "Str Mages?"
date = 2012-11-16
media = ["text"]
subjects = ["general", "STR mage", "post-BB"]
domain = "reddit.com"
url = "https://old.reddit.com/r/Maplestory/comments/13bn69/str_mages/"
url_archived = "https://web.archive.org/web/20201228101000/https://old.reddit.com/r/Maplestory/comments/13bn69/str_mages/"

[[entries]]
title = "2015: General Odd-Job Discussion"
date = 2015-05-18
media = ["text"]
subjects = ["general", "post-BB"]
domain = "reddit.com"
url = "https://old.reddit.com/r/Maplestory/comments/36cdae/2015_general_oddjob_discussion/"
url_archived = "https://web.archive.org/web/20201228085257/https://old.reddit.com/r/Maplestory/comments/36cdae/2015_general_oddjob_discussion/"

[[entries]]
title = "KMS STR Mage Screen"
date = 2017-05-29
media = ["images", "text"]
subjects = ["STR mage", "fire/poison", "pre-BB"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20180311145509/https://www.basilmarket.com/KMS-STR-Mage-Screen-bbZzO"

[[entries]]
title = "KMS permanent beginner ranker(2003-2005) Screen"
date = 2017-05-29
media = ["images", "text"]
subjects = ["permabeginner", "pre-BB"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20180320175401/http://www.basilmarket.com/KMS-permanent-beginner-ranker-2003-2005--Screen-bbZzP"

[[entries]]
title = "The pioneer of poison mist str mage(KMS) Screen"
date = 2017-06-01
media = ["images", "text"]
subjects = ["STR mage", "fire/poison", "pre-BB"]
domain = "basilmarket.com"
url_archived = "https://web.archive.org/web/20170809123316/http://www.basilmarket.com/The-pioneer-of-poison-mist-str-mage-KMS--Screen-bbZzQ"

[[entries]]
title = "[KMS] 2017 Maplestory Camper - The last active Islander"
date = 2017-12-19
media = ["video", "audio"]
subjects = ["camper", "post-BB"]
domain = "youtube.com"
url = "https://www.youtube.com/watch?v=s9SXRQGwvRA"
